### ISSUE TITLE
2 issues with the dialog component on ipad safari

### ISSUE THREAD

**Issue by joepstender** [bluzky/salad_ui#17] opened 2024-06-24 07:40 UTC
On ipad (with safari):

1. The modal won’t open when you tap on it the first time. You have to tap it twice.
2. After closing the modal it redirects to a route that isn’t found. 

This is on https://salad-storybook.fly.dev/core_components/dialog

**Comment by bluzky** [comment] 2024-06-24 13:37
Thanks for reporting, I don't have an iPad. Let me try to reproduce on desktop

**Comment by joepstender** [comment] 2024-06-24 13:49
Here’s a recorded screenshot :-) if I can do anything let me know. https://vimeo.com/966712369

**Comment by kamaroly** [comment] 2024-06-24 18:15
@joepstender are you referring to the redirect when a user dismisses the modal/ dialog?

**Comment by joepstender** [comment] 2024-06-24 20:00
Yes, by tapping on the X in the top right side corner, or by tapping anywhere else on the screen.

**Comment by bluzky** [comment] 2024-06-25 15:25
Oh, it's because I open a new link on_cancel event. Updated the example.
The other issue happened on Safari for Mac too. I'm investigating

**Comment by bluzky** [comment] 2024-06-25 16:40
Now animation is handled by tailwind-animate and this issue would be fixed in PR #22

**Comment by joepstender** [comment] 2024-06-26 09:58
Indeed the redirection issue has been fixed on ipad! I still have to tap a second time on the button to open the modal though, which is not the case on https://ui.shadcn.com/docs/components/dialog. There only only one tap is enough. That issue might be hard to debug without an actual ipad…

**Comment by bluzky** [comment] 2024-06-26 15:33
I suspected that is storybook issue.
This issue occurred on my iPhone, but when I switch to playground, it doesn't happen any more

**Comment by joepstender** [comment] 2024-07-03 18:54
Yeah, I suppose we can close this issue.

**Closed** 2024-07-08 15:11 UTC
